// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ffalconesmera/payments-platform/merchants/repository (interfaces: MerchantRepository)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	model "github.com/ffalconesmera/payments-platform/merchants/model"
	gomock "github.com/golang/mock/gomock"
)

// MockMerchantRepository is a mock of MerchantRepository interface.
type MockMerchantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantRepositoryMockRecorder
}

// MockMerchantRepositoryMockRecorder is the mock recorder for MockMerchantRepository.
type MockMerchantRepositoryMockRecorder struct {
	mock *MockMerchantRepository
}

// NewMockMerchantRepository creates a new mock instance.
func NewMockMerchantRepository(ctrl *gomock.Controller) *MockMerchantRepository {
	mock := &MockMerchantRepository{ctrl: ctrl}
	mock.recorder = &MockMerchantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchantRepository) EXPECT() *MockMerchantRepositoryMockRecorder {
	return m.recorder
}

// CreateMerchant mocks base method.
func (m *MockMerchantRepository) CreateMerchant(arg0 context.Context, arg1 *model.PayMerchant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMerchant", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMerchant indicates an expected call of CreateMerchant.
func (mr *MockMerchantRepositoryMockRecorder) CreateMerchant(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMerchant", reflect.TypeOf((*MockMerchantRepository)(nil).CreateMerchant), arg0, arg1)
}

// FindMerchantByCode mocks base method.
func (m *MockMerchantRepository) FindMerchantByCode(arg0 context.Context, arg1 string) (*model.PayMerchant, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMerchantByCode", arg0, arg1)
	ret0, _ := ret[0].(*model.PayMerchant)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMerchantByCode indicates an expected call of FindMerchantByCode.
func (mr *MockMerchantRepositoryMockRecorder) FindMerchantByCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMerchantByCode", reflect.TypeOf((*MockMerchantRepository)(nil).FindMerchantByCode), arg0, arg1)
}

// FindMerchantById mocks base method.
func (m *MockMerchantRepository) FindMerchantById(arg0 context.Context, arg1 string) (*model.PayMerchant, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMerchantById", arg0, arg1)
	ret0, _ := ret[0].(*model.PayMerchant)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMerchantById indicates an expected call of FindMerchantById.
func (mr *MockMerchantRepositoryMockRecorder) FindMerchantById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMerchantById", reflect.TypeOf((*MockMerchantRepository)(nil).FindMerchantById), arg0, arg1)
}
