// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ffalconesmera/payments-platform/payments/externals/repository (interfaces: BankRepository)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	dto "github.com/ffalconesmera/payments-platform/payments/externals/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockBankRepository is a mock of BankRepository interface.
type MockBankRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBankRepositoryMockRecorder
}

// MockBankRepositoryMockRecorder is the mock recorder for MockBankRepository.
type MockBankRepositoryMockRecorder struct {
	mock *MockBankRepository
}

// NewMockBankRepository creates a new mock instance.
func NewMockBankRepository(ctrl *gomock.Controller) *MockBankRepository {
	mock := &MockBankRepository{ctrl: ctrl}
	mock.recorder = &MockBankRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankRepository) EXPECT() *MockBankRepositoryMockRecorder {
	return m.recorder
}

// ProcessPayment mocks base method.
func (m *MockBankRepository) ProcessPayment(arg0, arg1 string) (*dto.BankPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPayment", arg0, arg1)
	ret0, _ := ret[0].(*dto.BankPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockBankRepositoryMockRecorder) ProcessPayment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockBankRepository)(nil).ProcessPayment), arg0, arg1)
}

// ProcessRefund mocks base method.
func (m *MockBankRepository) ProcessRefund(arg0, arg1 string) (*dto.BankRefund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRefund", arg0, arg1)
	ret0, _ := ret[0].(*dto.BankRefund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessRefund indicates an expected call of ProcessRefund.
func (mr *MockBankRepositoryMockRecorder) ProcessRefund(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRefund", reflect.TypeOf((*MockBankRepository)(nil).ProcessRefund), arg0, arg1)
}
